# This file was generated by GoReleaser. DO NOT EDIT.
cask "firstgreenci" do
  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "9df37119da274de02d9044f7080bf8558c8fbc1e5e9e39d2d6beb4e640df1b7b"
      url "https://github.com/Dhafer84/firstgreenci/releases/download/v#{version}/firstgreenci_#{version}_macOS_AppleSilicon.tar.gz"
    end
    on_intel do
      sha256 "bcdaedb513d328a1978e5ac2ebc4f660ba223cc6907dfb5faef7764110cfece2"
      url "https://github.com/Dhafer84/firstgreenci/releases/download/v#{version}/firstgreenci_#{version}_macOS_Intel.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "78d4808d11a7055fc5e40b4951a9ded541a22b85917e6479f2455516d476fccf"
      url "https://github.com/Dhafer84/firstgreenci/releases/download/v#{version}/firstgreenci_#{version}_Linux_ARM64.tar.gz"
    end
    on_intel do
      sha256 "8912d4d94e86ae5b567e7f93a53c2a234ef1407124fad6f3b459d14c7a4edd8c"
      url "https://github.com/Dhafer84/firstgreenci/releases/download/v#{version}/firstgreenci_#{version}_Linux_x86-64.tar.gz"
    end
  end

  name "firstgreenci"
  desc "Takes your project to its first green CI pipeline, without writing any YAML"
  homepage "https://github.com/Dhafer84/firstgreenci"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "act",
    ]

  binary "firstgreenci"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/firstgreenci"]
  end

  # No zap stanza required

  caveats <<~EOS
    Docker doit être installé et démarré :
      https://www.docker.com/products/docker-desktop/
    Vérifiez que tout est prêt :  firstgreenci doctor

    Docker must be installed and running:
      https://www.docker.com/products/docker-desktop/
    Check that everything is ready:  firstgreenci doctor
  EOS
end
