# This file was generated by GoReleaser. DO NOT EDIT.
cask "firstgreenci" do
  version "0.1.7"

  on_macos do
    on_arm do
      sha256 "43fa981fca76e872bc3d0fd4d1bf5f9de861861d49d540f9ed47dbafba4dc0bb"
      url "https://github.com/Dhafer84/firstgreenci/releases/download/v#{version}/firstgreenci_#{version}_macOS_AppleSilicon.tar.gz"
    end
    on_intel do
      sha256 "84c3218b69e32e89be81cbcb0857973a93a916785948e5dc51b2ffa96eff1bce"
      url "https://github.com/Dhafer84/firstgreenci/releases/download/v#{version}/firstgreenci_#{version}_macOS_Intel.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1a07b8f1db2aa50ce2424390d456a5ab16bbfcfe2d6e175430c8aa3549dd9e8b"
      url "https://github.com/Dhafer84/firstgreenci/releases/download/v#{version}/firstgreenci_#{version}_Linux_ARM64.tar.gz"
    end
    on_intel do
      sha256 "9a7842ba7567a458d19b00873f3a3d31f54c2230df9afab7c870de3459eef03a"
      url "https://github.com/Dhafer84/firstgreenci/releases/download/v#{version}/firstgreenci_#{version}_Linux_x86-64.tar.gz"
    end
  end

  name "firstgreenci"
  desc "Takes your project to its first green CI pipeline, without writing any YAML"
  homepage "https://github.com/Dhafer84/firstgreenci"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "act",
    ]

  binary "firstgreenci"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/firstgreenci"]
  end

  # No zap stanza required

  caveats <<~EOS
    Docker doit être installé et démarré :
      https://www.docker.com/products/docker-desktop/
    Vérifiez que tout est prêt :  firstgreenci doctor

    Docker must be installed and running:
      https://www.docker.com/products/docker-desktop/
    Check that everything is ready:  firstgreenci doctor
  EOS
end
