# This file was generated by GoReleaser. DO NOT EDIT.
cask "firstgreenci" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "ac29a7de0acd62af7cf9018d505a57853bdb2bde32ad10ee61fa47b9690ad97d"
      url "https://github.com/Dhafer84/firstgreenci/releases/download/v#{version}/firstgreenci_#{version}_macOS_AppleSilicon.tar.gz"
    end
    on_intel do
      sha256 "458f618e4b836eee08d044c21dfef376ab89441cf40a730ebd0988b74e6572c5"
      url "https://github.com/Dhafer84/firstgreenci/releases/download/v#{version}/firstgreenci_#{version}_macOS_Intel.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "aeae7ac1b4d492aa940fc4f6e0571169f0bcb15cee8d78d08167f4a68f073790"
      url "https://github.com/Dhafer84/firstgreenci/releases/download/v#{version}/firstgreenci_#{version}_Linux_ARM64.tar.gz"
    end
    on_intel do
      sha256 "d0323cf4c30eed1394171179431c9d7531acfd8a6ca8f943a16a54c46bbe6129"
      url "https://github.com/Dhafer84/firstgreenci/releases/download/v#{version}/firstgreenci_#{version}_Linux_x86-64.tar.gz"
    end
  end

  name "firstgreenci"
  desc "Takes your project to its first green CI pipeline, without writing any YAML"
  homepage "https://github.com/Dhafer84/firstgreenci"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "act",
    ]

  binary "firstgreenci"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/firstgreenci"]
  end

  # No zap stanza required

  caveats <<~EOS
    Docker doit être installé et démarré :
      https://www.docker.com/products/docker-desktop/
    Vérifiez que tout est prêt :  firstgreenci doctor

    Docker must be installed and running:
      https://www.docker.com/products/docker-desktop/
    Check that everything is ready:  firstgreenci doctor
  EOS
end
